- name: "Deploy Ignite-UX"
  hosts: ignite_ux
  become: true
  roles:
    - lpars.hpux.ignite_ux

- name: "Deploy Integrity VM and manage VMs"
  hosts: integrity_vm
  become: true
  roles:
    - lpars.hpux.integrity_vm

- name: "Configure NTP"
  hosts: all
  become: true
  roles:
    - lpars.hpux.ntp
