---
- name: "Deploy Ignite-UX"
  hosts: ignite_ux
  become: true
  roles:
    - iambryant.hpux.ignite_ux

- name: "Deploy Integrity VM"
  hosts: integrity_vm
  become: true
  roles:
    - iambryant.hpux.integrity_vm

- name: "Ensure hosts are configured to a baseline"
  hosts: all
  become: true
  roles:
    - iambryant.hpux.ntp
